# Generated by Django 4.2.3 on 2023-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion',
            field=models.BooleanField(default=False, verbose_name='Статус Выполнения'),
        ),
    ]
